create table TERRITORIO(
	id int identity(1,1) NOT NULL,
	COD_REGIAO int not null,
	DESCRICAO char(10) null,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

create table ENVIO(
	id int identity(1,1) NOT NULL,
	FRETE decimal(10, 2) null,
	NOMENAVIO char(30) null,
	CIDADE char(30) null,
	REGIAO char(30) null,
	NOME_CATEGORIA char(30) null,
	DESCRICAO char(30) null,
	COD_CATEGORIA int not null,
	COD_ENVIO int not null,
	DHIN smalldatetime not null,
	FK_TERRITORIO int,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (10, 'Brasil')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (20, 'EUA')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (30, 'China')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (40, 'Japão')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (50, 'Suiça')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (60, 'Argentina')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (70, 'Uruguai')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (80, 'Alemanha')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (90, 'Canada')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (100, 'Chipre')
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (110, 'Egito')
/*
insert into TERRITORIO(COD_REGIAO, DESCRICAO) VALUES (110, 'Egito')*/

insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (1000.76, 'Estrela do Mar', 'São Paulo', 'Norte', 'Cereal', 'navio grande', 1, 1, '2022-10-10 10:10', 1)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (5000.56, 'Tempestade Azul', 'Nova York', 'Sudeste', 'Cenoura', 'navio pequeno', 2, 2, '2010-10-10 10:10', 2)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (7000.32, 'Navegador Celestial', 'Pequim', 'Sul', 'Bacalhau', 'navio medio', 3, 3, '2023-10-10 10:10', 3)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (2000.76, 'Vento Alado', 'Toquio', 'Norte', 'Abacate', 'navio grande', 4, 4, '2012-10-10 10:10', 4)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (3000.34, 'Odisseia Marítima', 'Zurique', 'Sudeste', 'Banana', 'navio grande', 5, 5, '2008-10-10 10:10', 5)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (5600.56, 'Aurora Marinha', 'Buenos Aires', 'Centro oeste', 'Uva', 'navio medio', 6, 6, '2000-10-10 10:10', 6)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (9000.21, 'Maré de Prata', 'Montevideo', 'noroeste', 'Feijao', 'navio medio', 7, 7, '1995-10-10 10:10', 7)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (1240.42, 'Dragão dos Mares', 'Berlim', 'Sul', 'Alecrim', 'navio medio', 8, 8, '1969-10-10 10:10', 8)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (1600.98, 'Peregrino Oceânico', 'Toronto', 'oeste', 'Babosa', 'navio pequeno', 9, 9, '1975-10-10 10:10', 9)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (6500.22, 'Lua Náutica', 'nicosia', 'oeste', 'Ameixa', 'navio grande', 10, 10, '2014-10-10 10:10', 10)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (6500.22, 'Lua Náutica', 'Cairo', 'Norte', 'Cereal', 'navio grande', 11, 11, '2011-10-10 10:10', 11)
/*
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (6500.22, 'Lua Náutica', 'Cairo', null, 'Cereal', 'navio grande', 12, 12, '2011-10-10 10:10', 12)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (6500.22, 'Lua Náutica', 'Cairo', null, 'Cereal', 'navio grande', 13, 13, '2011-08-08 10:10', 13)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (6500.22, 'Lua Náutica', 'Roraima', null, 'Cereal', 'navio grande', 14, 14, '2011-12-12 10:10', 14)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (6500.22, 'Lua ', 'Roraima', null, 'Cereal', 'navio grande', 15, 15, '2011-11-11 10:10', 15)
insert into ENVIO(FRETE, NOMENAVIO, CIDADE, REGIAO, NOME_CATEGORIA, DESCRICAO, COD_CATEGORIA, COD_ENVIO, DHIN, FK_TERRITORIO) VALUES (6500.22, 'Lua ', 'Roraima', null, 'Cereal', 'navio grande', 16, 16, '2010-11-11 10:10', 16)*/


select * from ENVIO
select * from TERRITORIO

/*
1 Select * from TERRITORIO order by COD_REGIAO desc 
2 Select * from ENVIO order by FRETE asc 
3 Select NOMENAVIO, CIDADE, REGIAO from ENVIO
4 Select NOME_CATEGORIA, DESCRICAO from ENVIO
5 select sum(COD_CATEGORIA) from ENVIO
6 select sum(COD_ENVIO) from ENVIO
7 select sum(FRETE) from TERRITORIO
8 select sum(COD_REGIAO) from TERRITORIO
9 select max(FRETE) from ENVIO
10 select min(FRETE) from ENVIO
11 select max(COD_CATEGORIA) from ENVIO
12 select min(COD_CATEGORIA) from ENVIO
13 select max(COD_ENVIO) from ENVIO
14 select min(COD_ENVIO) from ENVIO
15 select max(COD_REGIAO) from TERRITORIO
16 select min(COD_REGIAO) from TERRITORIO
17 select avg(FRETE) from ENVIO
18 select avg(COD_CATEGORIA) from ENVIO
19 select avg(COD_ENVIO) from ENVIO
20 select avg(COD_REGIAO) from TERRITORIO
21 select * from TERRITORIO WHERE COD_REGIAO = 20
22 select * FROM TERRITORIO WHERE COD_REGIAO IN (20, 30)
23 select * FROM TERRITORIO WHERE DESCRICAO LIKE 'S%'
24 select * FROM TERRITORIO WHERE COD_REGIAO LIKE '7%'
25 SELECT * FROM ENVIO JOIN TERRITORIO ON ENVIO.FK_TERRITORIO = TERRITORIO.id WHERE TERRITORIO.descricao = 'Brasil'
26 SELECT * FROM ENVIO WHERE FRETE > 50
27 SELECT * FROM ENVIO WHERE REGIAO is null
28 SELECT * FROM ENVIO WHERE DATEPART(MONTH, DHIN) = 8
29 SELECT * FROM ENVIO WHERE COD_ENVIO between 3 and 9
30 SELECT * FROM ENVIO WHERE CIDADE like 'r%'
31 SELECT * FROM ENVIO WHERE NOME_CATEGORIA <> 'Cereal'
32 SELECT NOME_CATEGORIA, COD_CATEGORIA FROM ENVIO WHERE COD_CATEGORIA < 5
33 SELECT count(FK_TERRITORIO) FROM ENVIO join TERRITORIO on ENVIO.FK_TERRITORIO = TERRITORIO.id where TERRITORIO.DESCRICAO = 'Alemanha'
34 SELECT count(id) FROM ENVIO where CIDADE = 'São Paulo'
35 SELECT count(FRETE) FROM ENVIO where CIDADE = 'São Paulo'
36 SELECT count(FRETE) FROM ENVIO where REGIAO = 'Sudeste'
37 SELECT count(COD_ENVIO) FROM ENVIO
38 SELECT * FROM ENVIO where REGIAO is not null
39 SELECT count(id) FROM TERRITORIO where COD_REGIAO = 20
40 SELECT count(id) FROM TERRITORIO where COD_REGIAO = 40
41 SELECT * FROM TERRITORIO where COD_REGIAO = 50 and DESCRICAO like 'S%'
42 SELECT * FROM ENVIO WHERE CIDADE IN ('Nova York', 'Pequim', 'Toquio');
43 SELECT * FROM ENVIO WHERE CIDADE not IN ('Nova York', 'Pequim', 'Toquio');
44 SELECT DISTINCT REGIAO FROM ENVIO
SELECT DISTINCT DESCRICAO FROM TERRITORIO
45 select * from ENVIO WHERE DATEPART(MONTH, DHIN) = 7
46 select * from ENVIO WHERE DATEPART(DAY, DHIN) = 10 and DATEPART(MONTH, DHIN) = 10 and DATEPART(YEAR, DHIN) = 2022
47 select * from ENVIO WHERE DATEPART(MONTH, DHIN) between 11 and 12 and DATEPART(YEAR, DHIN) = 2011
*/

select * from ENVIO WHERE DATEPART(MONTH, DHIN) between 11 and 12 and DATEPART(YEAR, DHIN) = 2011














